### ISSUE TITLE
Autoformat duplicates import line on saving

### ISSUE THREAD

**Issue by zamrokk** [mdx-js/mdx-analyzer#360]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/react@3.0.0

### Steps to reproduce

1. use Vscode with Format on Save feature
1. Save any file with some imports at the beginning
1. It duplicates an import and break the CI I have with vercel later

![image](https://github.com/mdx-js/mdx/assets/2536368/85fb2793-28ed-429c-b27d-2fb78605d96f)

### Expected behavior

Do not duplicate the import

### Actual behavior

it duplicates it

**Comment by remcohaszing** [comment]
Can you post contents of an MDX file where this issue occurs?

**Comment by zamrokk** [comment]
.mdx file extension is not allowed for upload  :'(

Do you prefer on .txt ?

**Comment by zamrokk** [comment]
You can try with maybe a simpler case

Here is the JSX component as example

![image](https://github.com/mdx-js/mdx-analyzer/assets/2536368/838b2b29-48bc-4dad-951d-85333c79426b)

**Comment by remcohaszing** [comment]
You can post code blocks on GitHub using tripe backticks as a code fence, like so:

````md
```mdx
import 'hello'

# Hello from MDX
```
````

**Comment by remcohaszing** [comment]
Based on your example, I am unable to reproduce the issue you’re describing. Are you sure it’s related to `vscode-mdx`, and not for example the [ESLint integration](https://github.com/mdx-js/eslint-mdx)?

**Comment by zamrokk** [comment]
If I use the MDX extension in VsCode + ````mdx` at the beginning of the mdx file, it is ok
If I do not use the MDX extension , it is ok
If I use the MDX extension but not ````mdx` it is ko

**Comment by zamrokk** [comment]
if I do manually Format with :
- prettier : no issue
- MDX : no issue

It is when I save the file ... I have autoformatting on save . I don't know who cause the import duplication on the chain of execution  o.O

**Comment by zamrokk** [comment]
Is it a good practice to prefix all mdx files with `  ```mdx   `  ?

**Comment by RobbyRabbitman** [comment]
+1

**Comment by coryetzkorn** [comment]
This is also happening to me.

`<PostVideo>` is getting duplicated when format-on-save runs (via the VSCode MDX extension).

I'm also using frontmatter, so that might be part of it. Other MDX files in my project work tho. Something weird about this file.

```mdx
---
title: Building Products People Love
subtitle: A look into product and design thinking at Notion.
date: 2020-05-19
tags: design, speaking, video
thumbnail: building-products-people-love.png
---

import PostImage from "@components/PostImage"
import PostVideo from "@components/PostVideo"
import PostVideo from "@components/PostVideo"

<PostImage
  src="building-products-people-love.png"
  alt="Build products people love"
/>

Building a product people love requires more than simply shipping features. It’s important to have a mission people believe in, an original brand, and an approach to product that always puts user needs first.

Thanks so much to the folks at Samsung NEXT for inviting me to speak in these crazy COVID-19 times!

<PostVideo id="EDRRwnwxMwU" />
```

**Comment by mathias-falkenberg** [comment]
Setting `"mdx.server.enable": false` in settings makes the issue disappear, so could it be related to this setting now being enabled by default?

**Comment by mathias-falkenberg** [comment]
Same issue here, even if I switch off ESLint and Prettier. However, if I set `"mdx.server.enable": false`, the issue disappears.

Could this issue have something to do with that setting now being `true` by default?

**Comment by remcohaszing** [comment]
This isn’t related to formatting. I managed to reproduce this issue using the following VS Code settings:

```jsonc
{
  "[mdx]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": "always"
    }
  }
}
```

The issue is gone when using the latest unreleased changes. I’m not sure what fixed this, but it’s fixed in the next release.

**Comment by mathias-falkenberg** [comment]
I'm still seeing this issue even with version 1.7.0 of the VScode MDX extension.

Toggling organize imports off will remove the error, but must be considered a workaround
  ```
"[mdx]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": "never"
    }
  }
```

**Comment by vicary** [comment]
I am using `v1.8.3` and the issue still exists. The codebase is tailwind's Protocol template, you may test with the attached source file [page.mdx](https://github.com/mdx-js/mdx-analyzer/files/14901084/page.mdx.txt).

Choosing _Organize Imports_ from the command palette triggers the bug, appending all imports at the end of file.

@remcohaszing sorry to bother, but shall we open a new issue or reopen this one?

**Comment by remcohaszing** [comment]
@vicary I’m not seeing this with the file you provided. Please provide an example repository with steps to reproduce.
